service: aws-node-rest-api-project

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:eu-west-2:715946337841:table/TodoTable

functions:
  getTodos:
    handler: src/getTodos.handler
    events:
      - http:
          path: /todos
          method: get
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /todos
          method: post
  getTodo:
    handler: src/getTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: put
  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: delete

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
